### PR TITLE
A recipe on merging and filtering Pandas Dataframes based on time-stamps

### PR DESCRIPTION
**Pull request by eternalscholar**
This is a recipe on merging and filtering data in Pandas DataFrames based on Time-stamps.

### CODE REVIEW

**Comment by eternalscholar** [comment]
It would be better to create two folders, images and data, within the Python folder for a neat organization.

**Comment by mikenutt** [comment]
Let's take a look at this in tomorrow's meeting!

**Comment by mikenutt** [comment]
@csbailey5t, @eternalscholar reports he is unable to create a Python/images folder. Can we give the Consultants those permissions?

**Comment by csbailey5t** [comment]
@eternalscholar you should already have permissions to push a folder. What error are you getting when trying to `git push`?

**Comment by eternalscholar** [comment]
@csbailey5t @mikenutt Thanks for your comments. I realized I have the right to create folders when I push the repository from the git command-line. I wasn't using the command line before, instead I was trying to do that online itself. I've closed this pull request and opened a new one with image and data folders included.

**Pull request closed without merging**
